
# Name of your site (displayed in the header)
name: Pinang

# Short bio or description (displayed in the header)
description: Pinjaman Tenang dari Bank BRI AGRO

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
